version: 2
jobs:
    test_portability_snap_atac:
        docker:
            - image: circleci/python:3.6.1
        steps:
            - checkout
            - run:
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install requests
                    python test/run_portability_test.py --test-directories test/snap_atac/pr/

    test_portability_bulk_rna_pipeline:
        docker:
            - image: circleci/python:3.6.1
        steps:
            - checkout
            - run:
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install requests
                    python test/run_portability_test.py --test-directories test/bulk_rna_pipeline/pr/

    test_portability_optimus:
        docker:
            - image: circleci/python:3.6.1
        steps:
            - checkout
            - run:
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install requests
                    python test/run_portability_test.py --test-directories test/optimus/pr/
                no_output_timeout: 1.5h

    test_portability_optimus_mouse:
        docker:
            - image: circleci/python:3.6.1
        steps:
            - checkout
            - run:
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install requests
                    python test/run_portability_test.py --test-directories test/optimus_mouse/pr
                no_output_timeout: 1.5h

    test_portability_smartseq2_single_sample:
        docker:
            - image: circleci/python:3.6.1
        steps:
            - checkout
            - run:
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install requests
                    python test/run_portability_test.py --test-directories test/smartseq2_single_sample/pr/
                no_output_timeout: 1.5h

    test_optimus:
        machine: true
        steps:
            - checkout
            - run:
                command: |
                    ./test/trigger_test.sh optimus
                no_output_timeout: 1.5h


    test_optimus_snrnaseq:
        machine: true
        steps:
            - checkout
            - run:
                command: |
                    ./test/trigger_test.sh optimus_snrnaseq
                no_output_timeout: 1.5h

    test_optimus_v3:
        machine: true
        steps:
            - checkout
            - run:
                command: |
                    ./test/trigger_test.sh optimus prV3
                no_output_timeout: 1.5h

    test_optimus_snrnaseq v3:
        machine: true
        steps:
            - checkout
            - run:
                command: |
                    ./test/trigger_test.sh optimus_srnaseq prV3
                no_output_timeout: 1.5h


    test_smartseq2:
        machine: true
        steps:
            - checkout
            - run:
                command: |
                    ./test/trigger_test.sh smartseq2_single_sample
                no_output_timeout: 1.5h

    test_smartseq2_multisample:
        machine: true
        steps:
            - checkout
            - run:
                command: |
                      ./test/trigger_test.sh smartseq2_multisample
                no_output_timeout: 1.5h

    test_smartseq2_multisample_single_end:
        machine: true
        steps:
            - checkout
            - run:
                  command: |
                      ./test/trigger_test.sh smartseq2_multisample pr_single_end
                  no_output_timeout: 1.5h

    test_smartseq2_single_end:
        machine: true
        steps:
            - checkout
            - run:
                command: |
                    ./test/trigger_test.sh smartseq2_single_sample pr_single_end
                no_output_timeout: 1.5h

    test_optimus_mouse:
        machine: true

        steps:
            - checkout
            - run:
                command: |
                    ./test/trigger_test.sh optimus_mouse
                no_output_timeout: 1.5h

    test_emptyDropsWrapper:
        docker:
            - image: quay.io/humancellatlas/secondary-analysis-dropletutils:0.1.0
        steps:
            - checkout
            - run:
                command: |
                    cd docker/emptydrops/emptyDropsWrapper/test/
                    ./test_emptyDropsWrapper.sh

    test_npz2rds:
        docker:
            - image: quay.io/humancellatlas/secondary-analysis-dropletutils:0.1.0
        steps:
            - checkout
            - run:
                command: |
                    cd docker/emptydrops/npz2rds/test/
                    ./test.sh

    test_bulk_rna:
        machine: true
        steps:
            - checkout
            - run:
                command: |
                    ./test/trigger_test.sh bulk_rna_pipeline
                no_output_timeout: 1.5h

    test_snap_atac:
        machine: true
        steps:
            - checkout
            - run:
                command: |
                    ./test/trigger_test.sh snap_atac
                no_output_timeout: 1.5h

    test_sc_atac:
       machine: true
       steps:
           - checkout
           - run:
               command: |
                   ./test/trigger_test.sh sc_atac
               no_output_timeout: 1.5h
               
workflows:
    version: 2
    test_all:
        jobs:
          - test_optimus
#          - test_optimus_mouse
#          - test_smartseq2
#          - test_smartseq2_single_end
#          - test_emptyDropsWrapper
#          - test_npz2rds
#          - test_snap_atac
#          - test_sc_atac
#          - test_bulk_rna
#          - test_portability_snap_atac
#          - test_portability_bulk_rna_pipeline
#          - test_portability_optimus
#          - test_portability_optimus_mouse
#          - test_portability_smartseq2_single_sample
          - test_optimus_v3
#          - test_smartseq2_multisample
#          - test_smartseq2_multisample_single_end
	  - test_optimus_snrnaseq
 	  - test_optimus_snrnaseq_v3